# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-06-17 22:26
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0003_choice_dob'),
    ]

    operations = [
        migrations.AddField(
            model_name='choice',
            name='age',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
